### ISSUE TITLE
Setting channel order for a command

### ISSUE THREAD

**Issue by clintval** [evandam/evandam.conda#16]
Exciting! I too was using UDST/ansible-conda for awhile but the project looks unmaintained. How would I go about setting either the default channel order, or adding channels for an install command? See other feature request here: https://github.com/UDST/ansible-conda/issues/26

**Comment by evandam** [comment]
Hi @clintval, sorry for the delay. Like the project from UDST, this just passes the channels listed as command line arguments to conda. The order of the list provided should be preserved, but I'm unaware if there's a way to enforce any kind of ordering.

Alternatively, you could set config file first, and this would pick up the values you set.

Closing this out since I don't think it's a change that would be made here if you agree.

Thanks!

**Comment by clintval** [comment]
Thanks @evandam! Passing channels to `conda` only appends the channels to the list already defined in the configuration file. So, indeed, the solution would be to provide a `.condarc` with channels already set. I was hoping to see this as a first-class feature in the DSL of Ansible. If I find time to revisit this, I'll let you know!
