### ISSUE TITLE
conda not found in PATH, executable not specified

### ISSUE THREAD

**Issue by DavidNemeskey** [evandam/evandam.conda#18]
I get this error message when using the conda role without specifying `executable`. If I log in to the remote host, and `echo $PATH`, I see my conda directory in there -- but ansible doesn't find it. I guess this is because .bashrc is not executed in an ansible session; but then is it possible to use this module without specifying `executable` at all?

When I specify it, everything works fine (which, BTW, is great help, so thanks!).

Also, the parameter `executable` is not mentioned in the documentation.

**Comment by evandam** [comment]
Correct, if Ansible runs in a non-interactive session, it likely isn't going to load your profile. That's what the `executable` arg is for, or you can set the `PATH` environment variable in your playbook or task if you'd prefer.

Closing out since I don't think this is an issue here, but feel free to reopen!
