### ISSUE TITLE
Unable to specify Conda Build attribute in package install

### ISSUE THREAD

**Issue by mattmusich** [evandam/evandam.conda#19]
Hi evandam,

Love your work, we are looking to have a way to specify the Build attribute in Conda installs

For example `/usr/app/anaconda_root/bin/conda install --json jupyterhub=1.0.0=py37_0 ` the **=py37_0** is the part we are looking for added functionality.

Thanks bud.

**Comment by robromanowski** [comment]
+1. Have also ran into this issue, and the fix would be great.
This is a great module.

There are many times with specific use cases, where one may want to specify the exact build (of Python) with a specific package version (usually due to a multi Python-versioned environment.)

For example if one does a `conda search <package name>`:

```
└───$ conda search jupyter
Loading channels: done
# Name                       Version           Build  Channel
jupyter                        1.0.0          py27_4  pkgs/main
jupyter                        1.0.0          py27_6  pkgs/main
jupyter                        1.0.0          py27_7  pkgs/main
jupyter                        1.0.0  py27h505fd4b_0  pkgs/main
jupyter                        1.0.0          py35_4  pkgs/main
jupyter                        1.0.0          py35_6  pkgs/main
jupyter                        1.0.0          py35_7  pkgs/main
jupyter                        1.0.0  py35hd38625c_0  pkgs/main
jupyter                        1.0.0          py36_4  pkgs/main
jupyter                        1.0.0          py36_6  pkgs/main
jupyter                        1.0.0          py36_7  pkgs/main
jupyter                        1.0.0  py36h9896ce5_0  pkgs/main
jupyter                        1.0.0          py37_4  pkgs/main
jupyter                        1.0.0          py37_5  pkgs/main
jupyter                        1.0.0          py37_6  pkgs/main
jupyter                        1.0.0          py37_7  pkgs/main
```
There are many copies of `jupyter 1.0.0` but with different python builds. 

In normal conda land at command-line, one can specify: `conda install <package_name>=<version>=<build_string>`  (i.e. as @mattmusich alluded to above) `package=1.00=py36` or `package=1.0.0=py38`

I would also interested in this functionality since it allows a greater amount of customization!

_If one were to try and fork this repo and try to add this functionality in - would it be centered around the function for split_package_version? Something around adding in a build since you already parsing the version of the package?_

(where version I mean "version of package" and build I mean "build of python).

**Comment by evandam** [comment]
Hi friends :heart:

Documentation isn't updated (yet), but I just pushed `v1.2.0` to Galaxy, which allows you to specify something like this:

```yaml
- name: Install jupyter with a specific build
    conda:
      name: jupyter=1.0.0=py37_4
```

Can you bump your version and give it a shot?

**Comment by evandam** [comment]
I'm assuming this is fixed 🤷‍♂
