### ISSUE TITLE
Support (or document) using a conda requirements file

### ISSUE THREAD

**Issue by georgedorn** [evandam/evandam.conda#20]
Maybe this already works, maybe it doesn't, but if it does work it isn't documented.

Setting up my conda env looks like this:

`conda env create -n my_conda_env -f path/to/requirements/conda.yml`

I see no obvious way to specify that last parameter.

**Comment by evandam** [comment]
Hi @georgedorn 

This feature isn't implemented, and goes a bit against my original intent of the module. The configuration in a requirements file should be able to be passed as the module's arguments, making it more clear within your playbook what you're installing rather than having to go to the file.

I think it would be possible to handle supporting an environment file if needed, but to be honest I don't have the capacity as of now to implement it.

**Comment by evandam** [comment]
Closing this out for now 😅 

I don't have much capacity to work on this these days, but if anyone is interested in taking a stab at this if they find it useful that would be great!

**Comment by aehlke** [comment]
I think you could just state this intent very clearly in the readme and people would see the great value of this approach instead of getting surprised
